#!/usr/bin/env node
/**
 * render_gameplay_flow.js  —  Mermaid 版玩法流程图渲染器
 *
 * 用法: node render_gameplay_flow.js <case_dir>
 * 示例: node render_gameplay_flow.js outputs/case_04_eavesdrop
 *
 * 步骤:
 * 1. 读取 IR (ir_filled.json) 的 FLOW 维度
 * 2. 将 IR.FLOW 转换为 Mermaid flowchart 语法 (.mmd)
 * 3. 调用 mmdc (Mermaid CLI) 渲染为 SVG
 * 4. 嵌入到 bubble_chart HTML 模板
 *
 * 依赖: mmdc (npm install -g @mermaid-js/mermaid-cli)
 */

const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

// ─── 功能类型着色（与 02_skill_router.md 一致） ─────────────────────────────

const NODE_CLASSES = {
  start:      { fill: "#F5F5F5", stroke: "#999",    name: "state_neutral" },
  end:        { fill: "#F5F5F5", stroke: "#999",    name: "state_neutral" },
  event:      { fill: "#F3E5F5", stroke: "#9C27B0", name: "event_trigger" },
  decision:   { fill: "#E8F5E9", stroke: "#4CAF50", name: "condition" },
  action:     { fill: "#FFF8E1", stroke: "#FF9800", name: "player_action" },
  cutscene:   { fill: "#E3F2FD", stroke: "#2196F3", name: "system_action" },
  dialogue:   { fill: "#E3F2FD", stroke: "#2196F3", name: "system_action" },
  failure:    { fill: "#FFF3E0", stroke: "#FF9800", name: "failure" },
  forced_exit:{ fill: "#FFEBEE", stroke: "#F44336", name: "forced_exit" },
};
const DEFAULT_CLASS = { fill: "#F5F5F5", stroke: "#999", name: "state_neutral" };

function xmlEscape(s) {
  if (!s) return "";
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;").replace(/'/g, "&#39;");
}

// ─── IR.FLOW → Mermaid .mmd ───────────────────────────────────────────────

function buildMermaid(flow) {
  const nodes = flow.nodes || [];
  const edges = flow.edges || [];

  let mmd = "flowchart TD\n";

  // classDef 定义
  const classDefSet = new Set();
  for (const [type, cls] of Object.entries(NODE_CLASSES)) {
    if (!classDefSet.has(cls.name)) {
      classDefSet.add(cls.name);
      mmd += `    classDef ${cls.name} fill:${cls.fill},stroke:${cls.stroke},stroke-width:1.5px,color:#111\n`;
    }
  }
  mmd += "\n";

  // 节点定义
  for (const node of nodes) {
    const cls = NODE_CLASSES[node.type] || DEFAULT_CLASS;
    const label = node.name || node.id;

    if (node.type === "start" || node.type === "end") {
      // stadium 形
      mmd += `    ${node.id}([${label}]):::${cls.name}\n`;
    } else if (node.type === "decision") {
      // 菱形
      mmd += `    ${node.id}{${label}}:::${cls.name}\n`;
    } else {
      // 矩形
      mmd += `    ${node.id}[${label}]:::${cls.name}\n`;
    }
  }
  mmd += "\n";

  // 边定义
  for (const edge of edges) {
    const label = edge.label || "";
    if (edge.type === "fail") {
      // 虚线箭头
      if (label) {
        mmd += `    ${edge.from} -.->|${label}| ${edge.to}\n`;
      } else {
        mmd += `    ${edge.from} -.-> ${edge.to}\n`;
      }
    } else if (edge.type === "optional") {
      // 虚线箭头
      if (label) {
        mmd += `    ${edge.from} -.->|${label}| ${edge.to}\n`;
      } else {
        mmd += `    ${edge.from} -.-> ${edge.to}\n`;
      }
    } else {
      // 实线箭头
      if (label) {
        mmd += `    ${edge.from} -->|${label}| ${edge.to}\n`;
      } else {
        mmd += `    ${edge.from} --> ${edge.to}\n`;
      }
    }
  }

  return mmd;
}

// ─── 组装 HTML ──────────────────────────────────────────────────────────────

function buildHtml(svgContent, irData, caseId) {
  const levelName = irData.level_name || caseId;
  const levelId = irData.level_id || caseId;
  const levelType = irData.type || "Unknown";
  const nodeCount = irData.FLOW?.nodes?.length || "?";
  const timestamp = new Date().toISOString().split("T")[0];

  return `<!--
    MODULE: bubble_chart (gameplay_flow mode)
    GENERATED BY: pipeline/render_gameplay_flow.js (Mermaid)
    DRAWING: Mermaid flowchart TD → mmdc → SVG
-->
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>玩法逻辑流程图 — ${xmlEscape(levelName)}</title>
    <style>
        :root {
            --bg-primary: #F4F4F0;
            --bg-secondary: #E8E8E4;
            --bg-card: #FFFFFF;
            --text-primary: #111111;
            --text-secondary: #333333;
            --text-muted: #666666;
            --accent: #FF4500;
            --border: #111111;
            --border-light: #CCCCCC;
            --green: #228B22;
        }
        * { margin:0; padding:0; box-sizing:border-box; }
        body { font-family:'Noto Sans SC',-apple-system,BlinkMacSystemFont,sans-serif; background:var(--bg-primary); color:var(--text-primary); line-height:1.6; }
        .module { max-width:1100px; margin:0 auto; padding:40px 32px; }
        .module-header { margin-bottom:32px; padding-bottom:20px; border-bottom:2px solid var(--border); }
        .module-badge { display:inline-block; font-size:11px; color:var(--accent); letter-spacing:2px; font-weight:500; text-transform:uppercase; margin-bottom:8px; }
        .module-header h1 { font-size:24px; font-weight:700; letter-spacing:-0.5px; margin-bottom:8px; }
        .module-meta { display:flex; gap:24px; flex-wrap:wrap; font-size:12px; color:var(--text-muted); }
        .legend { display:flex; flex-wrap:wrap; gap:12px; margin-bottom:24px; padding:16px 20px; background:var(--bg-card); border:1px solid var(--border-light); }
        .legend-title { width:100%; font-size:11px; color:var(--text-muted); letter-spacing:1px; text-transform:uppercase; margin-bottom:4px; }
        .legend-item { display:flex; align-items:center; gap:6px; font-size:11px; color:var(--text-secondary); }
        .legend-swatch { width:16px; height:16px; border:1.5px solid; }
        .legend-swatch.diamond { width:14px; height:14px; transform:rotate(45deg); }
        .legend-swatch.stadium { border-radius:8px; }
        .legend-line { width:24px; height:0; }
        .legend-line.main { border-top:2px solid var(--border); }
        .legend-line.dotted { border-top:2px dotted var(--text-muted); }
        .flowchart-container { background:var(--bg-card); border:2px solid var(--border); padding:32px 24px; display:flex; justify-content:center; overflow-x:auto; }
        .flowchart-container svg { max-width:100%; height:auto; }
        .module-footer { margin-top:24px; padding-top:16px; border-top:1px solid var(--border-light); display:flex; justify-content:space-between; font-size:11px; color:var(--text-muted); }
        @media print { body{background:white;} .module{padding:20px;} .flowchart-container{border:1px solid #ccc;} }
    </style>
</head>
<body>

<section class="module" data-module="bubble-chart" data-level-id="${xmlEscape(levelId)}">

    <div class="module-header">
        <div class="module-badge">[GAMEPLAY FLOW]</div>
        <h1>玩法逻辑流程图 — ${xmlEscape(levelName)}</h1>
        <div class="module-meta">
            <span>关卡 ID: ${xmlEscape(levelId)}</span>
            <span>类型: ${xmlEscape(levelType)}</span>
            <span>节点: ${nodeCount}</span>
            <span>生成时间: ${timestamp}</span>
        </div>
    </div>

    <div class="legend">
        <div class="legend-title">图例 — 节点按功能类型着色</div>
        <div class="legend-item"><div class="legend-swatch stadium" style="background:#F5F5F5; border-color:#999;"></div>起始/终止</div>
        <div class="legend-item"><div class="legend-swatch" style="background:#F3E5F5; border-color:#9C27B0;"></div>事件触发</div>
        <div class="legend-item"><div class="legend-swatch diamond" style="background:#E8F5E9; border-color:#4CAF50;"></div>条件判断</div>
        <div class="legend-item"><div class="legend-swatch" style="background:#FFF8E1; border-color:#FF9800;"></div>玩家操作/状态</div>
        <div class="legend-item"><div class="legend-swatch" style="background:#E3F2FD; border-color:#2196F3;"></div>系统响应</div>
        <div class="legend-item"><div class="legend-swatch" style="background:#FFF3E0; border-color:#FF9800;"></div>失败</div>
        <div class="legend-item" style="margin-left:12px"><div class="legend-line main"></div>主路径</div>
        <div class="legend-item"><div class="legend-line dotted"></div>失败/重试/可选</div>
    </div>

    <div class="flowchart-container">
        ${svgContent}
    </div>

    <div class="module-footer">
        <span>Level Design Agent · BubbleChart Skill v2.0 (gameplay_flow + Mermaid)</span>
        <span>数据来源: IR.FLOW + IR.MECHANIC · 渲染: Mermaid flowchart</span>
    </div>

</section>

</body>
</html>`;
}

// ─── Main ───────────────────────────────────────────────────────────────────

async function main() {
  const caseDir = process.argv[2];
  if (!caseDir) {
    console.error("用法: node render_gameplay_flow.js <case_dir>");
    process.exit(1);
  }

  const projectRoot = path.resolve(__dirname, "..");
  const casePath = path.resolve(projectRoot, caseDir);
  const htmlFile = path.join(casePath, "bubble_chart.html");
  const mmdFile = path.join(casePath, "bubble_chart.mmd");
  const svgFile = path.join(casePath, "bubble_chart_mermaid.svg");

  // 读取 IR
  const caseId = path.basename(casePath);
  const irPath = path.join(projectRoot, "test_cases", caseId, "ir_filled.json");
  if (!fs.existsSync(irPath)) {
    console.error(`找不到 IR: ${irPath}`);
    process.exit(1);
  }
  const irData = JSON.parse(fs.readFileSync(irPath, "utf-8"));

  if (!irData.FLOW || !irData.FLOW.nodes) {
    console.error("IR 缺少 FLOW.nodes");
    process.exit(1);
  }

  console.log(
    `读取 IR: ${irData.FLOW.nodes.length} 节点, ${irData.FLOW.edges.length} 边`
  );

  // 生成 .mmd
  const mmdContent = buildMermaid(irData.FLOW);
  fs.writeFileSync(mmdFile, mmdContent, "utf-8");
  console.log(`✓ 生成 Mermaid: ${mmdFile}`);

  // 调用 mmdc 渲染 SVG
  try {
    execSync(
      `mmdc -i "${mmdFile}" -o "${svgFile}" -t neutral -b transparent -w 1200`,
      { stdio: "pipe", timeout: 30000 }
    );
    console.log(`✓ mmdc 渲染: ${svgFile}`);
  } catch (err) {
    console.error(`mmdc 渲染失败: ${err.message}`);
    if (err.stderr) console.error(err.stderr.toString());
    process.exit(1);
  }

  // 读取 SVG
  let svgContent = fs.readFileSync(svgFile, "utf-8");
  // 移除 XML 声明和 doctype（如果有）
  svgContent = svgContent.replace(/<\?xml[^?]*\?>\s*/g, "");
  svgContent = svgContent.replace(/<!DOCTYPE[^>]*>\s*/g, "");

  // 组装 HTML
  const html = buildHtml(svgContent, irData, caseId);

  fs.writeFileSync(htmlFile, html, "utf-8");
  console.log(`✓ 输出: ${htmlFile}`);
}

main().catch((err) => {
  console.error("[ERR]", err);
  process.exit(1);
});
